"use strict"

// todo: fix them errors cuz this is all wrong do them with like IDS EACCES...
export const strerror = {
  [-13]: "permission denied",
  [-2]: "no such file or directory",
  [-1]: "unknown error",
  [0]: "success",
  [1]: "end of file",
  [2]: "getaddrinfo error",
  [3]: "permission denied",
  [4]: "resource temporarily unavailable",
  [5]: "address already in use",
  [6]: "address not available",
  [7]: "address family not supported",
  [8]: "connection already in progress",
  [9]: "bad file descriptor",
  [10]: "resource busy or locked",
  [11]: "software caused connection abort",
  [12]: "connection refused",
  [13]: "connection reset by peer",
  [14]: "destination address required",
  [15]: "bad address in system call argument",
  [16]: "host is unreachable",
  [17]: "interrupted system call",
  [18]: "invalid argument",
  [19]: "socket is already connected",
  [20]: "too many open files",
  [21]: "message too long",
  [22]: "network is down",
  [23]: "network is unreachable",
  [24]: "file table overflow",
  [25]: "no buffer space available",
  [26]: "not enough memory",
  [27]: "not a directory",
  [28]: "illegal operation on a directory",
  [29]: "machine is not on the network",
  [31]: "socket is not connected",
  [32]: "socket operation on non-socket",
  [33]: "operation not supported on socket",
  [34]: "no such file or directory",
  [35]: "function not implemented",
  [36]: "broken pipe",
  [37]: "protocol error",
  [38]: "protocol not supported",
  [39]: "protocol wrong type for socket",
  [40]: "connection timed out",
  [41]: "invalid Unicode character",
  [42]: "address family for hostname not supported",
  [44]: "servname not supported for ai_socktype",
  [45]: "ai_socktype not supported",
  [46]: "cannot send after transport endpoint shutdown",
  [47]: "file already exists",
  [48]: "no such process",
  [49]: "name too long",
  [50]: "operation not permitted",
  [51]: "too many symbolic links encountered",
  [52]: "cross-device link not permitted",
  [53]: "directory not empty",
  [54]: "no space left on device",
  [55]: "i/o error",
  [56]: "read-only file system",
  [57]: "no such device",
  [58]: "invalid seek",
  [59]: "operation canceled"
}
